import { Car, Dealer, Service, Warranty } from '@/types';
import { getCarImage } from './utils';

export const mockDealers: Dealer[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    mobile: '+919876543210',
    role: 'dealer',
    showroomName: 'Premium Auto Hub',
    location: 'Mumbai, Maharashtra',
    rating: 4.8,
    totalCars: 45,
    verified: true,
    followers: 1250,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    createdAt: '2023-01-15',
  },
  {
    id: '2',
    name: 'Amit Sharma',
    mobile: '+919876543211',
    role: 'dealer',
    showroomName: 'Elite Motors',
    location: 'Delhi, NCR',
    rating: 4.6,
    totalCars: 32,
    verified: true,
    followers: 890,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    createdAt: '2023-02-20',
  },
];

export const mockCars: Car[] = [
  {
    id: '1',
    dealerId: '1',
    dealerName: 'Premium Auto Hub',
    brand: 'Maruti Suzuki',
    model: 'Swift VXI',
    year: 2020,
    price: 650000,
    mileage: 35000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    owners: 1,
    images: [getCarImage(0), getCarImage(1), getCarImage(2)],
    thumbnail: getCarImage(0),
    location: 'Mumbai, Maharashtra',
    description: 'Well maintained Swift in excellent condition. Single owner, all service records available.',
    features: ['ABS', 'Airbags', 'Power Steering', 'AC', 'Music System'],
    inspectionStatus: 'completed',
    status: 'approved',
    views: 1250,
    likes: 45,
    createdAt: '2024-01-15',
    approvedAt: '2024-01-16',
  },
  {
    id: '2',
    dealerId: '1',
    dealerName: 'Premium Auto Hub',
    brand: 'Hyundai',
    model: 'Creta SX',
    year: 2021,
    price: 1450000,
    mileage: 28000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    owners: 1,
    images: [getCarImage(1), getCarImage(2), getCarImage(3)],
    thumbnail: getCarImage(1),
    location: 'Mumbai, Maharashtra',
    description: 'Premium SUV with all features. Accident free, well maintained.',
    features: ['Sunroof', 'Leather Seats', 'Cruise Control', 'Parking Sensors', 'Touchscreen'],
    inspectionStatus: 'completed',
    status: 'approved',
    views: 2100,
    likes: 89,
    createdAt: '2024-01-20',
    approvedAt: '2024-01-21',
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    title: 'Complete Car Inspection',
    subtitle: '150+ point inspection by certified mechanics',
    image_url: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600',
    price: 2999,
    discounted_price: 2499,
    final_price: 2499,
    discount_amount: 500,
    has_offer: true,
    offer_percentage: 16.67,
    is_offer_valid: true,
    duration: '2-3 hours',
    checks: ['Engine Check', 'Brake System', 'Suspension', 'Electrical', 'Body Inspection'],
  },
  {
    id: '2',
    title: 'RC Transfer Service',
    subtitle: 'Hassle-free RC transfer with documentation',
    image_url: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600',
    price: 4999,
    discounted_price: null,
    final_price: 4999,
    discount_amount: 0,
    has_offer: false,
    offer_percentage: null,
    is_offer_valid: false,
    duration: '7-10 days',
    checks: ['Document Verification', 'RTO Processing', 'NOC Handling', 'Home Pickup'],
  },
];

export const mockWarranties: Warranty[] = [
  {
    id: '1',
    title: 'Basic Warranty',
    subtitle: '6 months comprehensive warranty',
    image_url: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600',
    price: 9999,
    discounted_price: 8999,
    final_price: 8999,
    discount_amount: 1000,
    has_offer: true,
    offer_percentage: 10,
    is_offer_valid: true,
    validity_months: 6,
    checks: ['Engine', 'Transmission', 'Electrical'],
  },
  {
    id: '2',
    title: 'Premium Warranty',
    subtitle: '1 year comprehensive warranty with roadside assistance',
    image_url: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600',
    price: 17999,
    discounted_price: null,
    final_price: 17999,
    discount_amount: 0,
    has_offer: false,
    offer_percentage: null,
    is_offer_valid: false,
    validity_months: 12,
    checks: ['Engine', 'Transmission', 'Electrical', 'AC', 'Suspension', '24/7 Roadside Assistance'],
  },
];
